from .api import (  # noqa: F401
    ALL_HOOKS,
    CHAT_REPLY,
    CHAT_SEND,
    COMMAND,
    EVENT,
    HOOK_HELP,
    MENU,
    ON_LOAD,
    ON_UNLOAD,
    SETTINGS_ACTION,
    SYSTEM_PROMPT,
    PluginAPI,
    PluginError,
)
from .icons import (  # noqa: F401
    badge_icon,
    badge_pixmap,
    clear_cache as clear_icon_cache,
    plugin_icon,
    plugin_pixmap,
)
from .manager import (  # noqa: F401
    DEFAULT_DIR,
    MenuGroup,
    MenuItem,
    PluginInfo,
    PluginManager,
    PluginsPanel,
)
from .manifest import ICON_SUFFIXES, ManifestError, PluginManifest  # noqa: F401
from .pages import (  # noqa: F401
    FORM_TYPES,
    PLUGIN_CATEGORY,
    FormRow,
    PluginPages,
    SettingsPageSpec,
)

# 别再导出名叫 manager 的单例，会覆盖同名子包；用 stlibs.plugin_manager()。

__all__ = [
    "ALL_HOOKS",
    "CHAT_REPLY",
    "CHAT_SEND",
    "COMMAND",
    "DEFAULT_DIR",
    "EVENT",
    "FORM_TYPES",
    "HOOK_HELP",
    "ICON_SUFFIXES",
    "MENU",
    "ManifestError",
    "MenuGroup",
    "MenuItem",
    "ON_LOAD",
    "ON_UNLOAD",
    "PLUGIN_CATEGORY",
    "PluginAPI",
    "PluginError",
    "PluginInfo",
    "PluginManager",
    "PluginManifest",
    "PluginPages",
    "PluginsPanel",
    "SETTINGS_ACTION",
    "SYSTEM_PROMPT",
    "SettingsPageSpec",
    "FormRow",
    "badge_icon",
    "badge_pixmap",
    "clear_icon_cache",
    "plugin_icon",
    "plugin_pixmap",
]
